### PR TITLE
Resolve #14, resolve #15, resolve #17

### LINKED ISSUE #14: Fix actuation
Actuation is currently not working post-Hypercat update

### LINKED ISSUE #15: Time-series sensor ID should be a route parameter
For the [time-series API](https://github.com/me-box/databox-store-blob/blob/macaroons/README.md#time-series-data-note-this-may-move-to-ts-after-mozfest) (if that's even here and not its own repo?) we should have sensor_id be a [route parameter](http://expressjs.com/en/guide/routing.html#route-parameters) so that path permissions cover individual sensors for any given driver-store pair. E.g. `/api/data/:sensorID/latest`, and that way some apps could only have access to `[ "/api/data/accelerometer/latest", "/api/data/light/*" ]` while another has `"/api/data/*"` for example to replicate original behaviour.

### LINKED ISSUE #17: Expand WebSocket subscription system
Precursor to #13 and second part of #16.

I asked during the call whether data pulled through polling and data pushed live through WS should be controlled by different permissions, and the consensus was that yes they should.

In order to be consistent with how tokens are passed in other places (and also to give app devs less to learn) I think we should extend how WS streaming works.

Firstly, that streaming data (in or out via WS) should be separated from subscribing to data, and the authorization that will need to entail.

Secondly, that subscription should be by endpoint, which the store will understand to mean sensor or key. Since we already have authorization for paths, this would kill two birds with one stone (similar to #15).

I propose that for every item pushed to a store-hosted Hypercat catalogue, there should be an equivalent WS subscription endpoint. How this works exactly is not that important — we could have both as items in the catalogue automatically, or we could say that the driver has to push them to the catalogue (and thus control what data can be subscribed to at all), or we could have a metadata flag for things that are subscribable via WS.

For example, for the endpoint:

    /api/key/:key

we have the subscription endpoint similar to anything like:

    /subscribe/api/key/:key
    /subscribe/key/:key
    /subscribe/api/key/:key
    /sub/key/:key

We could decide on anything for the namespacing as long as it's `[something]/[original rest endpoint]`. Potentially also a way to unsubscribe, though that might be weird to have as a route, since that would mean you could allow an app to subscribe but forbid them from unsubscribing (maybe could be a GET/POST param for the same one instead).

So this way, just by controlling the path caveat, an app can have access to REST but not WS, or WS but not REST, or both (`"/(sub|api)/key/*"` as a permission), or neither. Since subscription to WS is done via a REST endpoint and not WS, the same macaroon/token passing system applies.

On subscribing, an event listener is registered somewhere to notify that container of new inputs. Containers still need to go through the WS handshake with proper auth (see #16) and this also identifies them to the store (kind of like a session cookie), so that the store knows which WS connections a subscribe request applies to.

So the advantages are:

- Permissions to access WS at all can be controlled separately (if it's at root, then with the path `"/"`, else `"/ws"` or `"/notif"` or something). We could even apply routes to WS connections for whatever purpose and have even more fine-grained control with the path caveat.
- All an app needs to do is open a WS connection as a client, then separately subscribe to stuff with normal requests. It would never actually have to send anything over WS to the store.
- All a driver needs to do is perform the WS handshake with their token on connection, then they can write normally without having to send over a token every time.
- Since subscription is by endpoint, path caveats apply, so no need to add additional complexity in checking permissions when a subscription request is made (though [that is certainly possible now](https://github.com/yousefamar/databox-store-blob/blob/5d66ea146b2fe08114db8dc32e1a7f95810af93c/src/lib/websockets/broadcastDataOverWebSocket.js#L11)) since you can just do it with paths.
- REST and WS for the same data have separate permissions, as they should.

If you guys think that's the way to go, I'd be happy to take a stab at it. I hope I explained that clearly enough, but let me know if something is unclear (I may have forgotten parts I was thinking of).

### PR DESCRIPTION
**Pull request by yousefamar**
Some pretty invasive and backwards-compatibility breaking changes, so any extra set of eyes would be much appreciated. I sprinkled a bunch of non-critical TODOs everywhere — mainly documenting endpoint responses on errors, and error handling. Added two extra that also need documenting: 409 if trying to subscribe to endpoints before connected via WS (just because there's no point to allow that anyway), and a 501 in place of the unsubscribe feature since I didn't implement that yet. The main conceptual TODO is #19, but it should work without anyway.

Edit: Oh, I didn't update readme, but it's basically everything in #15.

Edit 2: Also didn't update the tests which is why Travis is shouting since this breaks the old API.

P.S. Those issues will [close automatically](https://help.github.com/articles/closing-issues-via-commit-messages/) when we eventually merge to master.

### CODE REVIEW

**Comment by Toshbrown** [comment]
I'll take a look.

**Comment by Toshbrown** [comment]
@yousefamar overall it looks super clean :+1: 

I've pushed some changes to your repo for you to have a look at, some bug fixes and working tests. There are some routeing changes that I'm not sure about you might want to work your magic on them  see b8d4ec9.

I have not had a chance check the WS stuff yet but some basic test for that might help us find any issues.

**Comment by yousefamar** [comment]
Thanks! You spotted some pretty critical stuff that I completely overlooked.

Tomorrow morning I'll update endpoint docs in readme and have that in this PR too. Still not entirely set in stone, especially for timeseries, since you can REST e.g. `/read/ts/latest/light`, but subscribe to that with `/sub/ts/light`, so regex-y type caveats might look weird and be ambiguous (e.g. `/(sub|read)/ts/*/light` to catch both).

I imagine that that probably won't matter in the end though since the SLA to caveat transformation will likely not do fancy acrobatics and probably just list out all variations as separate paths.

**Comment by Toshbrown** [comment]
> I imagine that that probably won't matter in the end though since the SLA to caveat transformation will likely not do fancy acrobatics and probably just list out all variations as separate paths.

Agreed.

**Pull request merged**
